# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionHandel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('authentication_token', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOSRequestResolver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('sos_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='androidServer.SOSRequest')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=32, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sosrequestresolver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='androidServer.User'),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='androidServer.User'),
        ),
        migrations.AddField(
            model_name='sessionhandel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='androidServer.User'),
        ),
    ]
