# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('androidServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sosrequestresolver',
            unique_together=set([('user', 'sos_request')]),
        ),
    ]
