# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidServer', '0002_auto_20171026_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
