# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('androidServer', '0003_auto_20171027_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionHandel',
            new_name='SessionHandle',
        ),
    ]
